### ISSUE TITLE
BUG - large first_reply_time_business_minutes on tickets with no replies

### ISSUE THREAD

**Issue by annichia** [fivetran/dbt_zendesk#35]
**Are you a current Fivetran customer?** 
Maria Riolo, Data Analyst, Zearn

**Describe the bug**
In tickets with no replies, first_reply_time_business_minutes defaults to "business minutes from ticket creation to current time + 1000 hrs."

**Steps to reproduce**
1. Run normally on data including tickets with no replies
4. See errors in the first_reply_time_business_minutes column of zendesk__ticket_metrics table

**Expected behavior**
I would expect first_reply_time_business_minutes to be null in tickets with no replies.

**Project variables configuration**

```yml

# Name your package! Package names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'zearn_redshift'
version: 1.0.0
config-version: 2

# This setting configures which "profile" dbt uses for this project. Profiles contain
# database connection information, and should be configured in the  ~/.dbt/profiles.yml file
profile: 'zearn-redshift'

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that source models can be found
# in the "models/" directory. You probably won't need to change these!
source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_modules"

on-run-start:
  # create schemas so we don't run into errors with the on-run-end hooks
  # if only doing a partial build or e.g. just running dbt seed
  - "CREATE SCHEMA IF NOT EXISTS \"{{ target.schema }}_marts\""
  - "CREATE SCHEMA IF NOT EXISTS \"{{ target.schema }}_staging\""
  - "CREATE SCHEMA IF NOT EXISTS \"{{ target.schema }}_exports\""
  - "CREATE SCHEMA IF NOT EXISTS \"{{ target.schema }}_zendesk_staging\""

on-run-end:
  - "GRANT USAGE ON SCHEMA \"{{ target.schema }}_marts\" to group looker, group zearn_analytics, group zearn_product"
  - "GRANT USAGE ON SCHEMA \"{{ target.schema }}_exports\" to jitterbit_sfdc_export, group looker, group zearn_analytics, group zearn_product"
  - "GRANT USAGE ON SCHEMA \"{{ target.schema }}_staging\" to group looker, group zearn_analytics, group zearn_product"
  - "GRANT USAGE ON SCHEMA \"{{ target.schema }}_zendesk_staging\" to group looker, group zearn_analytics, group zearn_product"
  - "GRANT SELECT ON ALL TABLES IN SCHEMA \"{{ target.schema }}_marts\" TO group looker, group zearn_analytics, group zearn_product"
  - "GRANT SELECT ON ALL TABLES IN SCHEMA \"{{ target.schema }}_exports\" TO jitterbit_sfdc_export, group zearn_analytics"
  - "GRANT SELECT ON ALL TABLES IN SCHEMA \"{{ target.schema }}_staging\" TO group zearn_analytics, group looker"
  - "GRANT SELECT ON ALL TABLES IN SCHEMA \"{{ target.schema }}_zendesk_staging\" TO group zearn_analytics, group looker"

# You can define configurations for models in the `source-paths` directory here.
# Using these configurations, you can enable or disable models, change how they
# are materialized, and more!

# In this example config, we tell dbt to build all models in the example/ directory
# as views (the default). These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
  +bind: false

  zearn_redshift:
    +materialized: view
    staging:
      +materialized: view
      +schema: staging
      classification:
        +materialized: table
        support_tables:
          +materialized: table
      rostering:
        +materialized: table
      usage:
        +materialized: table
        +dist: user_id
        +sort: event_type, event_type_clean, created_at
    marts:
      +materialized: view
      +schema: marts
      summaries:
        +materialized: table
        +dist: user_id
        +sort: daydate
      exports:
        +materialized: table
        +schema: exports
  zendesk:
    +schema: staging
    intermediate:
      +schema: staging
    sla_policy:
      +schema: staging
    ticket_history:
      +schema: staging
vars:
  school_years: ['2012-2013', '2013-2014', '2014-2015', '2015-2016', '2016-2017', '2017-2018', '2018-2019', '2019-2020', '2020-2021']
  rostering_school_years: ['2016-2017', '2017-2018', '2018-2019', '2019-2020', '2020-2021']
  random_seed: 3655122572989899184
  burbio_table_date: "2020-01-01" #default value needed to generate docs
  burbio_file_name: fake_file.csv #default value needed to generate docs
  district_student_info_district_id: 0 #default value needed to generate docs
  zendesk_source:
    zendesk_database: production
    zendesk_schema: ft_zendesk

```

**Package Version**

```yml
packages:
  - package: fishtown-analytics/dbt_utils
    version: [">=0.3.0"]
  - package: fivetran/zendesk
    version: 0.4.1
```

**Warehouse**

 
- [ ] BigQuery
- [x] Redshift
- [ ] Snowflake
- [x] Postgres
- [ ] Databricks
- [ ] Other (provide details below)

**Additional context**

I suspect I know where this is coming from.

In int_zendesk__ticket_first_reply_time_business.sql:
```
 greatest(0,
      (
        {{ fivetran_utils.timestamp_diff(
          'ticket_schedules.schedule_created_at',
          'least(ticket_schedules.schedule_invalidated_at, min(first_reply_time.agent_responded_at))',
          'second') }}/60
        )) as raw_delta_in_minutes
```

and in int_zendesk__ticket_schedules.sql:

`coalesce(lead(schedule_created_at) over (partition by ticket_id order by schedule_created_at)            , {{ fivetran_utils.timestamp_add("hour", 1000, "" ~ dbt_utils.current_timestamp() ~ "") }} ) as schedule_invalidated_at`

So it looks to me like if there's no reply and `lead(schedule_created_at) over (partition by ticket_id order by schedule_created_at)` is null, then we'd end up with current time + 1000 hrs treated as first response time.

**Screenshots**

**Please indicate the level of urgency** 

We're just now working on getting our Zendesk data into Looker, and we ended up looking into this because we were seeing anomalously large average resolution and reply times - especially reply times - and normal looking medians.

This is something we can probably work around if needed, by filtering on reply counts (for reply times) and ticket status (for resolution times), but it would be really nice not to have to.

**Are you interested in contributing to this package?** 

- [ ] Yes, I can do this and open a PR for your review.
- [ ] Possibly, but I'm not quite sure how to do this. I'd be happy to do a live coding session with someone to get this fixed. 
- [x] No, I'd prefer if someone else fixed this.  I don't have the time and/or don't know what the root cause of the problem is.

**Comment by fivetran-joemarkiewicz** [comment]
Hi @annichia thanks for opening this ticket!

After looking over your Issue it clearly seems like this is unintended behavior of the package. The additional context you provided is fantastic and will definitely help us resolve this issue in a timely manner! We are currently coming to the end of this sprint and will plan for this Issue to be addressed in the next sprint (starting mid next week). As such, I will respond back here when we assign this Issue next week.

Thanks!

**Comment by annichia** [comment]
Thanks, great to hear!

**Comment by fivetran-joemarkiewicz** [comment]
Hi @annichia I was working on this request and think the issue you are seeing may actually have stemmed from Issue #32. Essentially the logic for tracking agent comments was capturing ALL agent comments and not just public ones. Therefore, some tickets that had no public response were still being logged as a response time because there were internal comments. 

I have confirmed this bug on my end using the `v0.4.1` release of the package. I will continue to investigate, but it may be helpful if you were able to install the latest `v0.5.1` release of the package and see if your issue persists.
```yml
packages:
  - package: fivetran/zendesk
    version: 0.5.1
```

FYI - A breaking change from v0.4 -> v0.5 exists in the form of custom schemas. You can easily override this if you do not want multiple schemas to be made for the various zendesk models.

**Comment by annichia** [comment]
Hi @fivetran-joemarkiewicz Oh, interesting, that could make sense! I'll give v0.5.1 a try and let you know if I still see the bug.

**Comment by fivetran-joemarkiewicz** [comment]
Hi @annichia just wanted to check in if the `v0.5.1` release of the package resolved the original issue you were seeing?

**Comment by annichia** [comment]
Hi @fivetran-joemarkiewicz - sorry, I've been out of email contact. I'm still seeing the issue with v0.5.1, both in first reply time and first resolution.

**Comment by fivetran-joemarkiewicz** [comment]
@annichia I have been trying to dig into this issue but can't seem to replicate the issue on my end 🤔 

I think it would be most helpful if we were able to set some time up this week during out dbt office hours to dive into this issue live. You can schedule some time using this [link](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours?month=2021-07). I look forward to chatting with you then!

Additionally, when digging into this issue I did find that a few of the reply time conversions were not matching up when using a date difference by minutes. As such, I changed the calendar reply times to convert from seconds to minutes for more accurate reporting. While this most likely will not solve the issue you are seeing, you can still try this branch with the below `packages.yml` config:

```yml
packages:
  - git: https://github.com/fivetran/dbt_zendesk.git
    revision: bug/reply-times-fix
    warn-unpinned: false
```

**Comment by annichia** [comment]
Great, thanks - I scheduled a slot for this coming Monday and I'll give that fix a try, just in case.

**Comment by fivetran-joemarkiewicz** [comment]
@annichia I was able to make the changes we discussed and also some additional updates. Would you be able to try the working branch and let me know if everything looks good before merging to `master`? 
```yml
packages:
  - git: https://github.com/fivetran/dbt_zendesk.git
    revision: bug/reply-times-fix
    warn-unpinned: false
```
Thanks!

**Comment by annichia** [comment]
Cool, trying this now.

**Comment by annichia** [comment]
Unfortunately, still seeing unrealistically large numbers in first_resolution_business_minutes and first_reply_time_business_minutes using that new package.

**Comment by fivetran-joemarkiewicz** [comment]
🤔 I would have thought that the below would have fixed the reply time large numbers...
https://github.com/fivetran/dbt_zendesk/blob/5df4d4e304b0ffec082d82681dd50b04f308e2b6/models/zendesk__ticket_metrics.sql#L178

I believe my updates to the calendar resolution times when applied to business should resolve the error. However, for reply times would you be able to confirm for one of the large reply times that the conditional mentioned above is true? Or does it seem like there could be something I am missing?

**Comment by annichia** [comment]
It looks like everything with status solved is fixed - the ones that are still showing large numbers are mostly deleted or closed, with a handful pending.

**Comment by fivetran-joemarkiewicz** [comment]
Okay I see. After thinking about it I understand that the status should not be a dependency in the above calculation. I have removed that dependency and also adjusted the first and full resolution times for business metrics. 

Would you be able to run `dbt deps` on the same branch I shared and run your models again to see if these changes fixed the discrepancies?

**Comment by annichia** [comment]
That fixed all the first_resolution_business_minutes entries! 

Still getting some unfeasibly high first_reply_time_business_minutes, but not in the same circumstances - these I'm seeing in cases where first_reply_time_calendar_minutes is null and count_public_comments > 0.

**Comment by fivetran-joemarkiewicz** [comment]
Nice, we are getting closer! 🎉 

Do you see that the count_public_agent_comments is > 0 for those unfeasibly high ones? I wonder if these are in fact null? I added a coalesce to my case when statement to assume a null value as 0 public agent comments. I did just push that change if you want to see if that worked.

**Comment by annichia** [comment]
Yeah, count_public_agent_comments > 0 for most of the one's I'm seeing

**Comment by fivetran-joemarkiewicz** [comment]
Interesting, If you take a look at the staging table `stg_zendesk__ticket_comment` for one of those tickets does the first public agent reply date closely correlate to the first reply time from the final table? 

I want to confirm with these ones where there are in fact comments that they are not just extremely late reply times.

**Comment by fivetran-joemarkiewicz** [comment]
@annichia were you able to look into my above comment by chance? I am hoping to merge this and other changes for Zendesk by the end of the week.

**Comment by annichia** [comment]
Sorry, I'm having some unrelated technical issues and haven't been able to
check this yet. I'll ask my colleague @mjirv if he can take a look.

**Comment by mjirv** [comment]
Hi @fivetran-joemarkiewicz. I spot checked some of them, and am seeing tickets with very high `first_reply_time_business_minutes` (up to a 499200 minutes) and `count_public_agent_comments` > 0 where the first actual public agent reply time (from `stg_zendesk__ticket_comment`) was within the same day or week.

**Comment by fivetran-joemarkiewicz** [comment]
Thanks for confirming this @mjirv. The updated case statement must be incorrect on my end. I will look into this some more and get back to you with an update.

**Comment by fivetran-joemarkiewicz** [comment]
After chatting with @mjirv over in dbt slack the fixes applied to the working branch have resolved the issue. I have since merged and cut a new release for `v0.5.2` of the dbt_zendesk package. This should be live on the dbt hub later today.

Please feel free to open a new issue if you have any other questions or considerations for the package. Thanks again!
